title: Meenakshi Chandramohan
logo: /assets/img/IMG-20181012-210211839.jpg
description: Has 17+ years of experience in Information Technology in the field of IBM Mainframes. Main strengths are strong programming skills in COBOL, PL/1, DB2, IMS-DB, JCL and REXX. Currently doing my masters in Data Science
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
